// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	balance "github.com/soundrussian/go-practicum-diploma/balance"

	mock "github.com/stretchr/testify/mock"
)

// Balance is an autogenerated mock type for the Balance type
type Balance struct {
	mock.Mock
}

// UserBalance provides a mock function with given fields: ctx, userID
func (_m *Balance) UserBalance(ctx context.Context, userID uint64) (*balance.UserBalance, error) {
	ret := _m.Called(ctx, userID)

	var r0 *balance.UserBalance
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *balance.UserBalance); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*balance.UserBalance)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
