// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Order is an autogenerated mock type for the Order type
type Order struct {
	mock.Mock
}

// AcceptOrder provides a mock function with given fields: ctx, userID, orderID
func (_m *Order) AcceptOrder(ctx context.Context, userID uint64, orderID string) error {
	ret := _m.Called(ctx, userID, orderID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, string) error); ok {
		r0 = rf(ctx, userID, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
